console.log("5" + 5);        // 55
console.log("5" - 5);        // 0
console.log("5" * 5);        // 25
console.log("10" / 2);       // 5
console.log(5 + true);       // 6
console.log("10" - true);    // 9
console.log("5" + true);     // 5true
console.log(5 + null);       // 5
console.log(5 + undefined);  // NaN